/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gr12.prj.view;

import com.gr12.prj.object.LichHoatDong;
import com.gr12.prj.utils.Validate_data;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author APC
 */
public class LichSuNhaVanHoa extends javax.swing.JFrame {

    /**
     * Creates new form LichSuNhaVanHoa
     */
    private DefaultTableModel defaultTableModel;
    LichHoatDong lhd = new LichHoatDong();
    ArrayList<LichHoatDong> listLHD = new ArrayList<>();
    Validate_data validate = new Validate_data();
    public LichSuNhaVanHoa() {
        //this.setAlwaysOnTop(true); // this interface is always on top
        this.setResizable(false); // not resizeble now
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight() - 50;
        System.out.println(xsize + "va" + ysize);
        this.setSize(xsize, ysize);
        
        setTitle("Lịch Sử Quản Lí Nhà Văn Hóa");
        loadFile();
        getData(listLHD);
    }
    public void saveFile() {

        try {
            BufferedWriter bw = null; //Khởi tạo
            FileWriter fw = null; //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            for (int i = 0; i < listLHD.size(); i++) {
                String row = ""; //tạo hàng rỗng
                // row = ""
                row = row + listLHD.get(i).getMaLich() + "\t";
                row = row + listLHD.get(i).getCMND() + "\t";
                row = row + listLHD.get(i).getThoiGian() + "\t";
                row = row + listLHD.get(i).getCongViec() + "\t";
                row = row + listLHD.get(i).getTrangThai() + "\n";

                data += row;
            }
            fw = new FileWriter("lichhoatdong.txt");
            bw = new BufferedWriter(fw);
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            //Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void loadFile() {
        try {
            BufferedReader br = null;
            FileReader fr = null;
           // listCS = new ArrayList<>(); //lưu ý
            fr = new FileReader("lichhoatdong.txt");
            br = new BufferedReader(fr);
            String s = null;

            try {
                while ((s = br.readLine()) != null) {
                    //Cắt chuỗi:
                    String arr[] = s.split("\t");
                    //Khởi tạo
                    LichHoatDong hd = new LichHoatDong();
                    hd.setMaLich(arr[0]);
                    hd.setCMND(arr[1]);
                    hd.setThoiGian(arr[2]);
                    hd.setCongViec(arr[3]);
                    hd.setTrangThai(arr[4]);
                    listLHD.add(hd);
                }
            } catch (IOException ex) {
                //Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void getData(ArrayList<LichHoatDong> listLHD) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã Lịch");
        defaultTableModel.addColumn("CMND người đặt");
        defaultTableModel.addColumn("Thời gian");
        defaultTableModel.addColumn("Công việc");
        defaultTableModel.addColumn("Trạng thái");

        for (LichHoatDong obj : listLHD) {
            Vector vector = new Vector();
            vector.add(obj.getMaLich());
            vector.add(obj.getCMND());
            vector.add(obj.getThoiGian());
            vector.add(obj.getCongViec());
            vector.add(obj.getTrangThai());
            defaultTableModel.addRow(vector);
        }
        tbl_lichHoatDong.setModel(defaultTableModel);
    }
    
      public String convertDateToString(Date date) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        return dateFormat.format(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_lichHoatDong = new javax.swing.JTable();
        date_tuKhoa = new com.toedter.calendar.JDateChooser();
        btn_timKiem = new javax.swing.JButton();
        btn_thoat1 = new javax.swing.JButton();
        doc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel16.setFont(new java.awt.Font("UTM American Sans", 0, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(65, 50, 122));
        jLabel16.setText("Lịch sử sử dụng nhà văn hóa");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(650, 50, 660, 90);

        tbl_lichHoatDong.setFont(new java.awt.Font("UTM Times", 0, 18)); // NOI18N
        tbl_lichHoatDong.setForeground(new java.awt.Color(65, 50, 122));
        tbl_lichHoatDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_lichHoatDong.setCellSelectionEnabled(true);
        tbl_lichHoatDong.setGridColor(new java.awt.Color(140, 123, 185));
        tbl_lichHoatDong.setSelectionBackground(new java.awt.Color(255, 153, 153));
        jScrollPane2.setViewportView(tbl_lichHoatDong);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(190, 330, 1540, 610);

        date_tuKhoa.setBackground(new java.awt.Color(140, 123, 185));
        date_tuKhoa.setForeground(new java.awt.Color(65, 50, 122));
        date_tuKhoa.setFont(new java.awt.Font("UTM Times", 0, 18)); // NOI18N
        jPanel1.add(date_tuKhoa);
        date_tuKhoa.setBounds(790, 250, 250, 60);

        btn_timKiem.setBackground(new java.awt.Color(65, 50, 122));
        btn_timKiem.setFont(new java.awt.Font("UTM God's Word", 0, 13)); // NOI18N
        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gr12/prj/images/outline_search_white_18dp.png"))); // NOI18N
        btn_timKiem.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timKiem);
        btn_timKiem.setBounds(1050, 250, 80, 60);

        btn_thoat1.setBackground(new java.awt.Color(65, 50, 122));
        btn_thoat1.setFont(new java.awt.Font("UTM God's Word", 0, 13)); // NOI18N
        btn_thoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gr12/prj/images/outline_arrow_back_ios_new_white_24dp.png"))); // NOI18N
        btn_thoat1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_thoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoat1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thoat1);
        btn_thoat1.setBounds(20, 10, 100, 90);

        doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gr12/prj/images/Artboard 1nen.png"))); // NOI18N
        doc.setText("jLabel1");
        jPanel1.add(doc);
        doc.setBounds(0, 0, 1920, 1000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        String tuKhoa =convertDateToString(date_tuKhoa.getDate());
         if (tuKhoa.equals("")) {
            getData(listLHD);
        } else {
            ArrayList<LichHoatDong> listTimKiem = new ArrayList<>();
            for (int i = 0; i < listLHD.size(); i++) {
                if (listLHD.get(i).getThoiGian().contains(tuKhoa)) {
                    listTimKiem.add(listLHD.get(i));
                }
            }
            getData(listTimKiem);
        }
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_thoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoat1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_thoat1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thoat1;
    private javax.swing.JButton btn_timKiem;
    private com.toedter.calendar.JDateChooser date_tuKhoa;
    private javax.swing.JLabel doc;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_lichHoatDong;
    // End of variables declaration//GEN-END:variables
}
